name: Feature Request
description: Suggest a new feature or improvement for gm
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want gm to do?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any context, design ideas, or alternatives considered.
    validations:
      required: false
